### ISSUE TITLE
need to refresh the page to see changes with react-router auth demo

### ISSUE THREAD

**Issue by fraserxu** [Kureev/browserify-react-live#6]
Hi @Kureev again, I'm trying to play with this module more and find some new issue:

Basically I copy all the code from the `react-router` **auth-flow** example [here](https://github.com/rackt/react-router/blob/0.13.x/examples/auth-flow/app.js) and want to check if the hot-reload stuff support the login state well(very important in my case as I don't want to do login again and again while development and I think this is a big reason why I need it so much).

![screen shot 2015-08-06 at 10 35 22 am](https://cloud.githubusercontent.com/assets/1183541/9102563/72d17f84-3c26-11e5-9e93-0ac714e49881.png)

The login state is **kept well** with hot-reload but the page become blank and I have to refresh to make it work. Any idea on this? 

I don't mind to refresh the browser but it would be cool if I don't have to.

**Comment by fraserxu** [comment]
Ah, I also forget to mention that there's some warning messages from the console as well that complaining about the router `contextType`. See :point_down: 

![screen shot 2015-08-06 at 10 37 49 am](https://cloud.githubusercontent.com/assets/1183541/9102591/bd4e6d24-3c26-11e5-9210-3e33a6846710.png)

**Comment by fraserxu** [comment]
Here's the code you can play with :point_right: https://github.com/fraserxu/browserify-react-live/tree/master/examples/01%20-%20Basic

**Comment by Kureev** [comment]
This issue leads us to one of the technical restriction: you can't write multiple components in the one file. I'll explain why: if you want your code to be live-patchable, you need to decorate your components by special code. The easiest way to do it - decorate `exports` or `module.export` statement. Now I'm trying to improve this behavior, but not sure I'll find an easy way to do it. 

For me number one prio now - make bundles "partially reloadable", because now, as you probably mentioned, any change re-run the whole app with prev state and I want to avoid it.

**Comment by Kureev** [comment]
@fraserxu I have a good news for you :) Now, with new major version `2.0.0`, you can try to decouple your main file and it should work. I'll try to do my best to test it ASAP.

**Comment by fraserxu** [comment]
Awesome! Let me give a try really quickly!

**Comment by Kureev** [comment]
@fraserxu Just a quick tips:
- Now you need to watch files instead of bundle. E.g. `components/*` instead of `dist/bundle.js`
- Every your component should use `exports` or `module.exports` to export itself (it means you can't have multiple classes in one file)
- Now `browserify-react-live` tries to update **only** the file you've changed. So it means you wouldn't have any magic side-effects form other files until you edit them

**Comment by fraserxu** [comment]
Why to watch files instead of `bundle.js`? IMO it's more reasonable to just pass in the entry file(`index.js` here) like watchify does as my js file might be everywhere. 

So the command will be like `node_modules/.bin/bfps index.js &`

I believe watchify does have some way of checking which file is being changed and only update the needed dependencies, I'm not sure how though.

**Comment by Kureev** [comment]
@fraserxu Because of the speed as least. Waiting big bundle to build (even if we're talking about watchify) is about 1-2 secs on my mac. With watching files your UI would be updated in 200-300ms, so x10 times faster on my machine. Usually, you have all your frontend in one folder, but even if you don't, you can always specify multiple watch paths. So the command now is `node_modules/.bin/bfps components/* &`.

Watchify does it like you say: cache all files and invalidate cache when some of the files changes and rebuild bundle from cached files. But the problem is that browserify doesn't support replacing those files (i.e. react components/modules) in the runtime. So that's why I made this tool :)

**Comment by fraserxu** [comment]
I guess I got some new issue again with my latest code https://github.com/fraserxu/browserify-react-live/tree/master/examples/01%20-%20Basic
1. I set up the code and run `npm start`, everything work great;
2. I change a [single line](https://github.com/fraserxu/browserify-react-live/blob/master/examples/01%20-%20Basic/components/Login.js#L39) and it throw me an error like this

![screen shot 2015-08-07 at 11 42 37 am](https://cloud.githubusercontent.com/assets/1183541/9128396/7dba28b8-3cfa-11e5-9569-e76f587f2b43.png)

Looks like the content needs to be patched is correct but there's some issue with the updated browser-pack.

I dig into the code for a while but haven't figure out why.

**Comment by Kureev** [comment]
Hm, I think I know why. It's all about deploys in 04:00AM :) I forgot to proxy my requires, so when I replace some module, I apply it without bundle scope and that's why module isn't found. `overrideRequire` function should try to resolve module from cache instead of direct require. I'll try to solve it ASAP. Thanks for helping me testing it!

**Comment by Kureev** [comment]
@fraserxu Your example works perfect in `2.0.1`+, please, check it out ;)

**Comment by Kureev** [comment]
@fraserxu So, does it work for you? Can I close this issue?

**Comment by fraserxu** [comment]
Thanks for the fix, it works great for now! Closing...

**Comment by Kureev** [comment]
Thanks for reporting it! Let me know if you would have any other issues :+1:
